name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIV_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use --lts
            export PATH="$HOME/.nvm/versions/node/v22.14.0/bin/pnpm:$PATH"
            cd ~/ayame-web-sdk-examples/
            git pull origin main
            pnpm install
            pnpm build
            cp -r ./dist ~/server/nginx/html
          
